source "https://rubygems.org"

gem 'sinatra'
gem 'sinatra-param'
gem 'sinatra-contrib'
gem 'rack-contrib'
gem 'shotgun'
gem 'dotenv'
gem 'mongoid'
gem 'carrierwave-mongoid'
gem 'sinatra-initializers'
gem 'sidekiq'
gem 'active_model_serializers'
gem 'mini_magick'
gem 'will_paginate_mongoid'
gem 'httparty'
